### ISSUE TITLE
Suggestion: Make `hardware.raspberry-pi.config-output` contain the textual output

### ISSUE THREAD

**Issue by lilyball** [tstat/raspberry-pi-nix#1]
It would be handy if `hardware.raspberry-pi.config-output` would contain an attrset with keys `text` and `package`, so that way I can use `nixos-option` to view the contents of the file without having to actually build it.

**Comment by tstat** [comment]
this is now available as `hardware.raspberry-pi.config-generated` https://github.com/tstat/raspberry-pi-nix/commit/24f5b92db86a01f5bda2e117726f5a0e39b0ec97
