### ISSUE TITLE
Bluetooth: hci0: BCM: Read controller features failed (-110)

### ISSUE THREAD

**Issue by zeronobody0** [tstat/raspberry-pi-nix#6]
I built an [image using this flake](https://codeberg.org/shitpostalotl/nixos/src/branch/main/hosts/pi.nix), however bluetooth does not work. See issue title as well as [full dmesg output](http://0x0.st/H1AS.txt).

**Comment by tstat** [comment]
At a glance I don't see what is wrong with your config. 

When you say you built an image, do you mean that you built an sd card image with `nix build '.#nixosConfigurations.rpi-example.config.system.build.sdImage'` and flashed it to an sd card?

**Comment by zeronobody0** [comment]
building: [yeah i think so](https://codeberg.org/shitpostalotl/nixos/src/commit/4332dde0e57d444f9d70dc515397f725fd27bb86/flake.nix#L40)
flashing: yes

**Comment by tstat** [comment]
Can you paste the output of `dtc -I fs /sys/firmware/devicetree/base`?

**Comment by zeronobody0** [comment]
That will take a while, as the pi doesn't seem to have networking capabilities, so I must recompile the image to add the dtc packadge.

**Comment by zeronobody0** [comment]
[yeah i dont think you want me to paste that directly here it's really long](http://0x0.st/H1mk.txt)

**Comment by tstat** [comment]
I see, I inadvertently broke bluetooth with a recent change to get uart kernel output on boot. It should be working now on master, and the latest release doesn't have this problem.
