### ISSUE TITLE
License

### ISSUE THREAD

**Issue by K-Finlay** [tstat/raspberry-pi-nix#7]
Have you considered adding a license to this project?
I would love to use this in a project, but I am unable due to the lack of a license.

As per the GitHub FAQ:
>You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The [Open Source Guide](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) provides additional guidance on choosing the correct license for your project.

**Comment by tstat** [comment]
Oh yeah, an oversight on my part.

I added an MIT license in: https://github.com/tstat/raspberry-pi-nix/commit/409f6368c679b5902ec21f7d7d7721fa03d3e21e
